version: '2'
services:
    springdemo-app:
        image: springdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://springdemo-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=springDemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    springdemo-mongodb:
        extends:
            file: mongodb.yml
            service: springdemo-mongodb
